import { SupabaseClient } from '@supabase/supabase-js'

// ============================================================
// Type definitions
// ============================================================

export interface AIConfig {
  // Model & Thinking
  modelOpus: string
  modelSonnet: string
  defaultModel: 'opus' | 'sonnet'
  simpleSignalsRegex: string
  simpleMessageMaxLength: number
  thinkingEnabled: boolean
  thinkingBudgetTokens: number
  chatMaxTokens: number
  // Chat
  chatMaxIterations: number
  chatHistoryLimit: number
  chatContextTypes: string[]
  titleGenerationEnabled: boolean
  titleMaxTokens: number
  suggestionsLimit: number
  promptSizeWarning: number
  // Agent defaults
  agentDefaultModel: string
  agentDefaultMaxIterations: number
  agentDefaultTokenBudget: number
  agentDefaultTools: string[]
  // Upload
  uploadMaxFileSizeMB: number
  uploadMaxFiles: number
  uploadTextTruncationLimit: number
  uploadSignedUrlExpiry: number
  // Learning
  learningMaxInPrompt: number
  learningDefaultConfidence: number
  learningReinforcementIncrement: number
  learningCorrectionConfidence: number
  // Brand
  brandCentreName: string
  brandCentreNameUpper: string
  brandEntityName: string
  brandSENumber: string
  brandLocation: string
  brandTagline: string
  brandPrimaryColour: string
  brandGoldColour: string
  brandQAColours: string[]
  // Display
  displayDocPreviewLength: number
  displayContextSnippetLength: number
  displayAgentSummaryLength: number
  // Marketing
  marketingDefaultAdVariations: number
  marketingDefaultReviewTone: string
  marketingAnalyticsLookbackDays: number
  // Widget
  widgetMaxStoredMessages: number
  widgetWidthPx: number
  widgetHeightPx: number
  widgetSpeechLanguage: string
  // Reports
  reportMaxExportRows: number
  reportPreviewRowLimit: number
  // Cron
  cronQualificationWarningDays: number
  cronDocumentRetryLimit: number
  // SharePoint
  sharepointTokenExpirySeconds: number
  // Dashboard
  dashboardQipWeightElements: number
  dashboardQipWeightTasks: number
  dashboardQipWeightCompliance: number
  dashboardQipWeightTraining: number
  // Compliance
  complianceMandatoryQualifications: string[]
}

export interface BrandConfig {
  primary: string
  primaryRgb: { r: number; g: number; b: number }
  gold: string
  goldRgb: { r: number; g: number; b: number }
  centreName: string
  centreNameUpper: string
  seNumber: string
  entityName: string
  location: string
  tagline: string
}

// ============================================================
// Hardcoded defaults (fallback when DB is unavailable)
// ============================================================

const DEFAULTS: AIConfig = {
  modelOpus: 'claude-opus-4-20250514',
  modelSonnet: 'claude-sonnet-4-20250514',
  defaultModel: 'opus',
  simpleSignalsRegex: '^(hi|hello|hey|thanks|thank you|ok|yes|no|sure|got it|cheers|bye|good morning|good afternoon)\\b',
  simpleMessageMaxLength: 50,
  thinkingEnabled: true,
  thinkingBudgetTokens: 10000,
  chatMaxTokens: 16384,
  chatMaxIterations: 5,
  chatHistoryLimit: 60,
  chatContextTypes: ['qip_goal', 'qip_strategy', 'philosophy_principle', 'service_value', 'leadership_goal'],
  titleGenerationEnabled: true,
  titleMaxTokens: 30,
  suggestionsLimit: 20,
  promptSizeWarning: 100000,
  agentDefaultModel: 'sonnet',
  agentDefaultMaxIterations: 5,
  agentDefaultTokenBudget: 8192,
  agentDefaultTools: ['search_centre_context', 'get_qa_progress', 'get_overdue_items', 'get_policies', 'get_policy_detail', 'get_checklists', 'get_checklist_detail', 'get_documents', 'read_document_content', 'get_room_data'],
  uploadMaxFileSizeMB: 10,
  uploadMaxFiles: 10,
  uploadTextTruncationLimit: 50000,
  uploadSignedUrlExpiry: 3600,
  learningMaxInPrompt: 30,
  learningDefaultConfidence: 0.8,
  learningReinforcementIncrement: 0.05,
  learningCorrectionConfidence: 0.9,
  brandCentreName: 'Kiros Early Education',
  brandCentreNameUpper: 'KIROS EARLY EDUCATION',
  brandEntityName: 'HWAW Kirollos Childcare Pty Ltd',
  brandSENumber: 'SE-00017066',
  brandLocation: 'Bidwill, NSW',
  brandTagline: 'Generated by Kiros AI Assistant',
  brandPrimaryColour: '#470DA8',
  brandGoldColour: '#EDC430',
  brandQAColours: ['#e74c3c', '#e67e22', '#2ecc71', '#3498db', '#9b59b6', '#1abc9c', '#34495e'],
  displayDocPreviewLength: 500,
  displayContextSnippetLength: 150,
  displayAgentSummaryLength: 300,
  marketingDefaultAdVariations: 3,
  marketingDefaultReviewTone: 'empathetic',
  marketingAnalyticsLookbackDays: 30,
  widgetMaxStoredMessages: 20,
  widgetWidthPx: 420,
  widgetHeightPx: 550,
  widgetSpeechLanguage: 'en-AU',
  reportMaxExportRows: 10000,
  reportPreviewRowLimit: 50,
  cronQualificationWarningDays: 30,
  cronDocumentRetryLimit: 5,
  sharepointTokenExpirySeconds: 3600,
  dashboardQipWeightElements: 0.4,
  dashboardQipWeightTasks: 0.3,
  dashboardQipWeightCompliance: 0.2,
  dashboardQipWeightTraining: 0.1,
  complianceMandatoryQualifications: ['first_aid', 'cpr', 'anaphylaxis', 'asthma', 'child_protection', 'wwcc', 'food_safety'],
}

// ============================================================
// Helper: parse config value to typed value
// ============================================================

function parseValue(value: string, type: string): string | number | boolean | string[] {
  switch (type) {
    case 'int': return parseInt(value, 10) || 0
    case 'float': return parseFloat(value) || 0
    case 'bool': return value === 'true'
    case 'json': try { return JSON.parse(value) } catch { return value }
    default: return value
  }
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result ? { r: parseInt(result[1], 16), g: parseInt(result[2], 16), b: parseInt(result[3], 16) } : { r: 0, g: 0, b: 0 }
}

// ============================================================
// Main loader: loads ALL config in one query
// ============================================================

export async function loadAIConfig(supabase: SupabaseClient): Promise<AIConfig> {
  try {
    const { data, error } = await supabase.from('ai_config').select('config_key, config_value, value_type')
    if (error || !data) return { ...DEFAULTS }

    const map = new Map(data.map((r: { config_key: string; config_value: string; value_type: string }) => [r.config_key, parseValue(r.config_value, r.value_type)]))

    return {
      modelOpus: (map.get('model.opus_id') as string) || DEFAULTS.modelOpus,
      modelSonnet: (map.get('model.sonnet_id') as string) || DEFAULTS.modelSonnet,
      defaultModel: ((map.get('model.default') as string) || DEFAULTS.defaultModel) as 'opus' | 'sonnet',
      simpleSignalsRegex: (map.get('model.simple_signals_regex') as string) || DEFAULTS.simpleSignalsRegex,
      simpleMessageMaxLength: (map.get('model.simple_message_max_length') as number) || DEFAULTS.simpleMessageMaxLength,
      thinkingEnabled: map.has('model.thinking_enabled') ? (map.get('model.thinking_enabled') as boolean) : DEFAULTS.thinkingEnabled,
      thinkingBudgetTokens: (map.get('model.thinking_budget_tokens') as number) || DEFAULTS.thinkingBudgetTokens,
      chatMaxTokens: (map.get('model.chat_max_tokens') as number) || DEFAULTS.chatMaxTokens,
      chatMaxIterations: (map.get('chat.max_iterations') as number) || DEFAULTS.chatMaxIterations,
      chatHistoryLimit: (map.get('chat.history_limit') as number) || DEFAULTS.chatHistoryLimit,
      chatContextTypes: (map.get('chat.context_types') as string[]) || DEFAULTS.chatContextTypes,
      titleGenerationEnabled: map.has('chat.title_generation_enabled') ? (map.get('chat.title_generation_enabled') as boolean) : DEFAULTS.titleGenerationEnabled,
      titleMaxTokens: (map.get('chat.title_max_tokens') as number) || DEFAULTS.titleMaxTokens,
      suggestionsLimit: (map.get('chat.suggestions_limit') as number) || DEFAULTS.suggestionsLimit,
      promptSizeWarning: (map.get('chat.prompt_size_warning') as number) || DEFAULTS.promptSizeWarning,
      agentDefaultModel: (map.get('agent.default_model') as string) || DEFAULTS.agentDefaultModel,
      agentDefaultMaxIterations: (map.get('agent.default_max_iterations') as number) || DEFAULTS.agentDefaultMaxIterations,
      agentDefaultTokenBudget: (map.get('agent.default_token_budget') as number) || DEFAULTS.agentDefaultTokenBudget,
      agentDefaultTools: (map.get('agent.default_tools') as string[]) || DEFAULTS.agentDefaultTools,
      uploadMaxFileSizeMB: (map.get('upload.max_file_size_mb') as number) || DEFAULTS.uploadMaxFileSizeMB,
      uploadMaxFiles: (map.get('upload.max_files') as number) || DEFAULTS.uploadMaxFiles,
      uploadTextTruncationLimit: (map.get('upload.text_truncation_limit') as number) || DEFAULTS.uploadTextTruncationLimit,
      uploadSignedUrlExpiry: (map.get('upload.signed_url_expiry') as number) || DEFAULTS.uploadSignedUrlExpiry,
      learningMaxInPrompt: (map.get('learning.max_in_prompt') as number) || DEFAULTS.learningMaxInPrompt,
      learningDefaultConfidence: (map.get('learning.default_confidence') as number) || DEFAULTS.learningDefaultConfidence,
      learningReinforcementIncrement: (map.get('learning.reinforcement_increment') as number) || DEFAULTS.learningReinforcementIncrement,
      learningCorrectionConfidence: (map.get('learning.correction_confidence') as number) || DEFAULTS.learningCorrectionConfidence,
      brandCentreName: (map.get('brand.centre_name') as string) || DEFAULTS.brandCentreName,
      brandCentreNameUpper: (map.get('brand.centre_name_upper') as string) || DEFAULTS.brandCentreNameUpper,
      brandEntityName: (map.get('brand.entity_name') as string) || DEFAULTS.brandEntityName,
      brandSENumber: (map.get('brand.se_number') as string) || DEFAULTS.brandSENumber,
      brandLocation: (map.get('brand.location') as string) || DEFAULTS.brandLocation,
      brandTagline: (map.get('brand.tagline') as string) || DEFAULTS.brandTagline,
      brandPrimaryColour: (map.get('brand.primary_colour') as string) || DEFAULTS.brandPrimaryColour,
      brandGoldColour: (map.get('brand.gold_colour') as string) || DEFAULTS.brandGoldColour,
      brandQAColours: (map.get('brand.qa_colours') as string[]) || DEFAULTS.brandQAColours,
      displayDocPreviewLength: (map.get('display.doc_preview_length') as number) || DEFAULTS.displayDocPreviewLength,
      displayContextSnippetLength: (map.get('display.context_snippet_length') as number) || DEFAULTS.displayContextSnippetLength,
      displayAgentSummaryLength: (map.get('display.agent_summary_length') as number) || DEFAULTS.displayAgentSummaryLength,
      marketingDefaultAdVariations: (map.get('marketing.default_ad_variations') as number) || DEFAULTS.marketingDefaultAdVariations,
      marketingDefaultReviewTone: (map.get('marketing.default_review_tone') as string) || DEFAULTS.marketingDefaultReviewTone,
      marketingAnalyticsLookbackDays: (map.get('marketing.analytics_lookback_days') as number) || DEFAULTS.marketingAnalyticsLookbackDays,
      widgetMaxStoredMessages: (map.get('widget.max_stored_messages') as number) || DEFAULTS.widgetMaxStoredMessages,
      widgetWidthPx: (map.get('widget.width_px') as number) || DEFAULTS.widgetWidthPx,
      widgetHeightPx: (map.get('widget.height_px') as number) || DEFAULTS.widgetHeightPx,
      widgetSpeechLanguage: (map.get('widget.speech_language') as string) || DEFAULTS.widgetSpeechLanguage,
      reportMaxExportRows: (map.get('report.max_export_rows') as number) || DEFAULTS.reportMaxExportRows,
      reportPreviewRowLimit: (map.get('report.preview_row_limit') as number) || DEFAULTS.reportPreviewRowLimit,
      cronQualificationWarningDays: (map.get('cron.qualification_warning_days') as number) || DEFAULTS.cronQualificationWarningDays,
      cronDocumentRetryLimit: (map.get('cron.document_retry_limit') as number) || DEFAULTS.cronDocumentRetryLimit,
      sharepointTokenExpirySeconds: (map.get('sharepoint.token_expiry_seconds') as number) || DEFAULTS.sharepointTokenExpirySeconds,
      dashboardQipWeightElements: (map.get('dashboard.qip_weight_elements') as number) || DEFAULTS.dashboardQipWeightElements,
      dashboardQipWeightTasks: (map.get('dashboard.qip_weight_tasks') as number) || DEFAULTS.dashboardQipWeightTasks,
      dashboardQipWeightCompliance: (map.get('dashboard.qip_weight_compliance') as number) || DEFAULTS.dashboardQipWeightCompliance,
      dashboardQipWeightTraining: (map.get('dashboard.qip_weight_training') as number) || DEFAULTS.dashboardQipWeightTraining,
      complianceMandatoryQualifications: (map.get('compliance.mandatory_qualifications') as string[]) || DEFAULTS.complianceMandatoryQualifications,
    }
  } catch {
    return { ...DEFAULTS }
  }
}

// ============================================================
// Tool permissions loader
// ============================================================

export async function loadToolPermissions(supabase: SupabaseClient, toolType: 'main' | 'marketing' = 'main'): Promise<Map<string, string[]>> {
  try {
    const { data, error } = await supabase
      .from('ai_tool_permissions')
      .select('tool_name, allowed_roles')
      .eq('tool_type', toolType)
      .eq('is_active', true)
    if (error || !data) return new Map()
    return new Map(data.map((r: { tool_name: string; allowed_roles: string[] }) => [r.tool_name, r.allowed_roles]))
  } catch {
    return new Map()
  }
}

// ============================================================
// Document styles loader
// ============================================================

export async function loadDocumentStyles(supabase: SupabaseClient, format: string): Promise<Record<string, unknown>> {
  try {
    const { data, error } = await supabase
      .from('ai_document_styles')
      .select('styles')
      .eq('format', format)
      .single()
    if (error || !data) return {}
    return data.styles as Record<string, unknown>
  } catch {
    return {}
  }
}

// ============================================================
// Brand config builder (from AIConfig)
// ============================================================

export function buildBrandConfig(config: AIConfig): BrandConfig {
  return {
    primary: config.brandPrimaryColour,
    primaryRgb: hexToRgb(config.brandPrimaryColour),
    gold: config.brandGoldColour,
    goldRgb: hexToRgb(config.brandGoldColour),
    centreName: config.brandCentreName,
    centreNameUpper: config.brandCentreNameUpper,
    seNumber: config.brandSENumber,
    entityName: config.brandEntityName,
    location: config.brandLocation,
    tagline: config.brandTagline,
  }
}

// Export defaults for use as fallbacks in other files
export { DEFAULTS as AI_CONFIG_DEFAULTS }
