import React from 'react'
import {
  Document,
  Page,
  View,
  Text,
  Image,
  StyleSheet,
  renderToBuffer,
  Font,
} from '@react-pdf/renderer'
import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  BorderStyle,
} from 'docx'
import ExcelJS from 'exceljs'
import MarkdownIt from 'markdown-it'
import fs from 'fs'
import path from 'path'

// Load logo once at module init for embedding in exports
let LOGO_BASE64: string | null = null
let LOGO_BUFFER: Buffer | null = null
try {
  const logoPath = path.join(process.cwd(), 'public', 'logo.jpg')
  LOGO_BUFFER = fs.readFileSync(logoPath)
  LOGO_BASE64 = `data:image/jpeg;base64,${LOGO_BUFFER.toString('base64')}`
} catch {
  // Logo not available — headers will be text-only
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DocumentOptions {
  title: string
  content: string // Markdown
  recipient?: string
  author?: string
  date?: string
  format: 'pdf' | 'docx' | 'xlsx' | 'html' | 'md' | 'json'
}

// ---------------------------------------------------------------------------
// Brand constants
// ---------------------------------------------------------------------------

const BRAND = {
  primary: '#470DA8',
  primaryRgb: { r: 71, g: 13, b: 168 },
  centreName: 'Kiros Early Education',
  location: 'Bidwill, NSW',
  tagline: 'Generated by Kiros AI Assistant',
} as const

// ---------------------------------------------------------------------------
// Shared markdown helpers
// ---------------------------------------------------------------------------

const md = new MarkdownIt({ html: false, linkify: true, typographer: true })

interface MarkdownBlock {
  type:
    | 'heading'
    | 'paragraph'
    | 'list-item'
    | 'table'
    | 'blockquote'
    | 'code'
  level?: number // heading level 1-6
  text: string
  bold?: boolean
  rows?: string[][] // for tables
}

/**
 * Very lightweight markdown-to-block parser. We lean on markdown-it to
 * tokenise, then walk the token stream to produce simple block descriptors
 * that each export backend can render natively.
 */
function parseMarkdownBlocks(markdown: string): MarkdownBlock[] {
  const tokens = md.parse(markdown, {})
  const blocks: MarkdownBlock[] = []
  let i = 0

  while (i < tokens.length) {
    const token = tokens[i]

    if (token.type === 'heading_open') {
      const level = parseInt(token.tag.replace('h', ''), 10)
      const inline = tokens[i + 1]
      blocks.push({
        type: 'heading',
        level,
        text: inline?.content ?? '',
      })
      i += 3 // heading_open, inline, heading_close
      continue
    }

    if (token.type === 'paragraph_open') {
      const inline = tokens[i + 1]
      blocks.push({
        type: 'paragraph',
        text: inline?.content ?? '',
      })
      i += 3
      continue
    }

    if (token.type === 'bullet_list_open' || token.type === 'ordered_list_open') {
      i += 1
      let itemIndex = 1
      while (i < tokens.length && tokens[i].type !== 'bullet_list_close' && tokens[i].type !== 'ordered_list_close') {
        if (tokens[i].type === 'list_item_open') {
          i += 1
          // list items can contain paragraph_open/inline/paragraph_close or just inline
          if (i < tokens.length && tokens[i].type === 'paragraph_open') {
            const inline = tokens[i + 1]
            const prefix = token.type === 'ordered_list_open' ? `${itemIndex}. ` : '\u2022 '
            blocks.push({
              type: 'list-item',
              text: prefix + (inline?.content ?? ''),
            })
            itemIndex++
            i += 3 // paragraph_open, inline, paragraph_close
          }
        } else {
          i += 1
        }
      }
      i += 1 // skip list close
      continue
    }

    if (token.type === 'table_open') {
      const rows: string[][] = []
      i += 1
      while (i < tokens.length && tokens[i].type !== 'table_close') {
        if (tokens[i].type === 'tr_open') {
          const row: string[] = []
          i += 1
          while (i < tokens.length && tokens[i].type !== 'tr_close') {
            if (tokens[i].type === 'th_open' || tokens[i].type === 'td_open') {
              const inline = tokens[i + 1]
              row.push(inline?.content ?? '')
              i += 3
            } else {
              i += 1
            }
          }
          rows.push(row)
        }
        i += 1
      }
      if (rows.length > 0) {
        blocks.push({ type: 'table', text: '', rows })
      }
      i += 1
      continue
    }

    if (token.type === 'blockquote_open') {
      i += 1
      let quoteText = ''
      while (i < tokens.length && tokens[i].type !== 'blockquote_close') {
        if (tokens[i].type === 'paragraph_open') {
          const inline = tokens[i + 1]
          quoteText += (inline?.content ?? '') + '\n'
          i += 3
        } else {
          i += 1
        }
      }
      blocks.push({ type: 'blockquote', text: quoteText.trim() })
      i += 1
      continue
    }

    if (token.type === 'fence' || token.type === 'code_block') {
      blocks.push({ type: 'code', text: token.content })
      i += 1
      continue
    }

    i += 1
  }

  return blocks
}

/** Strip simple inline markdown formatting for plain-text contexts */
function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    .replace(/_(.+?)_/g, '$1')
    .replace(/`(.+?)`/g, '$1')
    .replace(/\[(.+?)\]\(.+?\)/g, '$1')
}

/** Check if inline text contains bold markers */
function hasBold(text: string): boolean {
  return /\*\*(.+?)\*\*/.test(text) || /__(.+?)__/.test(text)
}

function formatDate(date?: string): string {
  if (date) return date
  return new Date().toLocaleDateString('en-AU', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

// ---------------------------------------------------------------------------
// 1. PDF Generation — @react-pdf/renderer
// ---------------------------------------------------------------------------

const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 80,
    paddingBottom: 60,
    paddingHorizontal: 50,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
    color: '#1a1a1a',
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 50,
    backgroundColor: BRAND.primary,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 50,
  },
  headerText: {
    color: '#ffffff',
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
  },
  headerDate: {
    color: '#ffffff',
    fontSize: 9,
  },
  titleSection: {
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: BRAND.primary,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.primary,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#666666',
  },
  heading1: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: BRAND.primary,
    marginTop: 18,
    marginBottom: 6,
  },
  heading2: {
    fontSize: 15,
    fontFamily: 'Helvetica-Bold',
    color: '#333333',
    marginTop: 14,
    marginBottom: 4,
  },
  heading3: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: '#444444',
    marginTop: 10,
    marginBottom: 4,
  },
  paragraph: {
    fontSize: 11,
    marginBottom: 8,
    lineHeight: 1.6,
  },
  boldText: {
    fontFamily: 'Helvetica-Bold',
  },
  listItem: {
    fontSize: 11,
    marginBottom: 4,
    paddingLeft: 16,
    lineHeight: 1.5,
  },
  blockquote: {
    fontSize: 11,
    fontStyle: 'italic',
    color: '#555555',
    marginBottom: 8,
    paddingLeft: 16,
    borderLeftWidth: 3,
    borderLeftColor: BRAND.primary,
  },
  codeBlock: {
    fontSize: 9,
    fontFamily: 'Courier',
    backgroundColor: '#f5f5f5',
    padding: 10,
    marginBottom: 8,
    borderRadius: 3,
  },
  tableRow: {
    flexDirection: 'row' as const,
    borderBottomWidth: 1,
    borderBottomColor: '#dddddd',
  },
  tableHeaderRow: {
    flexDirection: 'row' as const,
    backgroundColor: BRAND.primary,
    borderBottomWidth: 1,
    borderBottomColor: BRAND.primary,
  },
  tableCell: {
    flex: 1,
    padding: 6,
    fontSize: 9,
  },
  tableHeaderCell: {
    flex: 1,
    padding: 6,
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 50,
    right: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#dddddd',
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: '#999999',
  },
})

function renderPdfBlock(block: MarkdownBlock, index: number): React.ReactElement {
  const key = `block-${index}`

  switch (block.type) {
    case 'heading': {
      const style =
        block.level === 1
          ? pdfStyles.heading1
          : block.level === 2
            ? pdfStyles.heading2
            : pdfStyles.heading3
      return React.createElement(Text, { key, style }, stripInlineMarkdown(block.text))
    }

    case 'paragraph': {
      const plain = stripInlineMarkdown(block.text)
      if (hasBold(block.text)) {
        // Render with bold segments
        const parts = block.text.split(/(\*\*[^*]+\*\*|__[^_]+__)/g)
        const children = parts.map((part, pi) => {
          const boldMatch = part.match(/^\*\*(.+)\*\*$/) || part.match(/^__(.+)__$/)
          if (boldMatch) {
            return React.createElement(
              Text,
              { key: `${key}-p-${pi}`, style: pdfStyles.boldText },
              boldMatch[1]
            )
          }
          return stripInlineMarkdown(part)
        })
        return React.createElement(Text, { key, style: pdfStyles.paragraph }, ...children)
      }
      return React.createElement(Text, { key, style: pdfStyles.paragraph }, plain)
    }

    case 'list-item':
      return React.createElement(
        Text,
        { key, style: pdfStyles.listItem },
        stripInlineMarkdown(block.text)
      )

    case 'blockquote':
      return React.createElement(
        View,
        { key, style: pdfStyles.blockquote },
        React.createElement(Text, null, stripInlineMarkdown(block.text))
      )

    case 'code':
      return React.createElement(Text, { key, style: pdfStyles.codeBlock }, block.text)

    case 'table': {
      if (!block.rows || block.rows.length === 0) {
        return React.createElement(View, { key })
      }
      const [headerRow, ...dataRows] = block.rows
      const tableChildren: React.ReactElement[] = []

      // Header
      tableChildren.push(
        React.createElement(
          View,
          { key: `${key}-th`, style: pdfStyles.tableHeaderRow },
          ...headerRow.map((cell, ci) =>
            React.createElement(
              Text,
              { key: `${key}-th-${ci}`, style: pdfStyles.tableHeaderCell },
              stripInlineMarkdown(cell)
            )
          )
        )
      )

      // Data rows
      dataRows.forEach((row, ri) => {
        tableChildren.push(
          React.createElement(
            View,
            { key: `${key}-tr-${ri}`, style: pdfStyles.tableRow },
            ...row.map((cell, ci) =>
              React.createElement(
                Text,
                { key: `${key}-tr-${ri}-${ci}`, style: pdfStyles.tableCell },
                stripInlineMarkdown(cell)
              )
            )
          )
        )
      })

      return React.createElement(
        View,
        { key, style: { marginBottom: 10 } },
        ...tableChildren
      )
    }

    default:
      return React.createElement(View, { key })
  }
}

export async function generatePdfDocument(
  title: string,
  content: string,
  options: DocumentOptions
): Promise<Buffer> {
  const dateStr = formatDate(options.date)
  const blocks = parseMarkdownBlocks(content)

  const headerView = React.createElement(
    View,
    { style: pdfStyles.header, fixed: true },
    ...(LOGO_BASE64
      ? [React.createElement(Image, { key: 'logo', src: LOGO_BASE64, style: { height: 36, width: 80, marginRight: 10 } })]
      : []),
    React.createElement(Text, { style: pdfStyles.headerText }, BRAND.centreName),
    React.createElement(Text, { style: pdfStyles.headerDate }, dateStr)
  )

  const titleSection = React.createElement(
    View,
    { style: pdfStyles.titleSection },
    React.createElement(Text, { style: pdfStyles.title }, title),
    options.recipient
      ? React.createElement(Text, { style: pdfStyles.subtitle }, `Prepared for: ${options.recipient}`)
      : null,
    options.author
      ? React.createElement(Text, { style: pdfStyles.subtitle }, `Author: ${options.author}`)
      : null
  )

  const footerView = React.createElement(
    View,
    { style: pdfStyles.footer, fixed: true },
    React.createElement(Text, { style: pdfStyles.footerText }, BRAND.tagline),
    React.createElement(
      Text,
      { style: pdfStyles.footerText, render: ({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }) => `Page ${pageNumber} of ${totalPages}` },
    )
  )

  const bodyBlocks = blocks.map((block, i) => renderPdfBlock(block, i))

  const page = React.createElement(
    Page,
    { size: 'A4', style: pdfStyles.page },
    headerView,
    titleSection,
    ...bodyBlocks,
    footerView
  )

  const doc = React.createElement(Document, {
    title,
    author: options.author ?? BRAND.centreName,
    creator: BRAND.tagline,
  }, page)

  const buffer = await renderToBuffer(doc)
  return Buffer.from(buffer)
}

// ---------------------------------------------------------------------------
// 2. Word Document — docx
// ---------------------------------------------------------------------------

function markdownToDocxParagraphs(blocks: MarkdownBlock[]): Paragraph[] {
  const paragraphs: Paragraph[] = []

  for (const block of blocks) {
    switch (block.type) {
      case 'heading': {
        const level =
          block.level === 1
            ? HeadingLevel.HEADING_1
            : block.level === 2
              ? HeadingLevel.HEADING_2
              : HeadingLevel.HEADING_3
        paragraphs.push(
          new Paragraph({
            heading: level,
            children: parseInlineRuns(block.text),
            spacing: { before: 240, after: 120 },
          })
        )
        break
      }

      case 'paragraph':
        paragraphs.push(
          new Paragraph({
            children: parseInlineRuns(block.text),
            spacing: { after: 120 },
          })
        )
        break

      case 'list-item':
        paragraphs.push(
          new Paragraph({
            children: parseInlineRuns(block.text),
            spacing: { after: 60 },
            indent: { left: 360 },
          })
        )
        break

      case 'blockquote':
        paragraphs.push(
          new Paragraph({
            children: [
              new TextRun({
                text: stripInlineMarkdown(block.text),
                italics: true,
                color: '555555',
              }),
            ],
            spacing: { after: 120 },
            indent: { left: 480 },
            border: {
              left: {
                color: '470DA8',
                space: 8,
                style: BorderStyle.SINGLE,
                size: 6,
              },
            },
          })
        )
        break

      case 'code':
        paragraphs.push(
          new Paragraph({
            children: [
              new TextRun({
                text: block.text,
                font: 'Courier New',
                size: 18,
              }),
            ],
            spacing: { after: 120 },
            shading: { fill: 'f5f5f5' },
          })
        )
        break

      case 'table': {
        if (block.rows && block.rows.length > 0) {
          const tableRows = block.rows.map((row, ri) =>
            new TableRow({
              children: row.map(
                (cell) =>
                  new TableCell({
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: stripInlineMarkdown(cell),
                            bold: ri === 0,
                            color: ri === 0 ? 'ffffff' : '1a1a1a',
                            size: 20,
                          }),
                        ],
                      }),
                    ],
                    shading: ri === 0 ? { fill: '470DA8' } : undefined,
                  })
              ),
            })
          )

          const colCount = block.rows[0].length || 1
          paragraphs.push(
            new Paragraph({ spacing: { before: 120 } })
          )
          // We cannot push a Table into Paragraph[], so we use a workaround:
          // docx library allows Table in the document sections children.
          // We'll tag it onto the paragraphs array — the caller must handle it.
          ;(paragraphs as unknown as (Paragraph | Table)[]).push(
            new Table({
              rows: tableRows,
              width: { size: 100, type: WidthType.PERCENTAGE },
            })
          )
          paragraphs.push(
            new Paragraph({ spacing: { after: 120 } })
          )
        }
        break
      }
    }
  }

  return paragraphs
}

/** Parse inline markdown (bold, italic) into TextRun[] */
function parseInlineRuns(text: string): TextRun[] {
  const runs: TextRun[] = []
  // Split on bold (**text** or __text__) patterns
  const parts = text.split(/(\*\*[^*]+\*\*|__[^_]+__)/g)
  for (const part of parts) {
    const boldMatch = part.match(/^\*\*(.+)\*\*$/) || part.match(/^__(.+)__$/)
    if (boldMatch) {
      runs.push(new TextRun({ text: stripInlineMarkdown(boldMatch[1]), bold: true }))
    } else if (part.length > 0) {
      runs.push(new TextRun({ text: stripInlineMarkdown(part) }))
    }
  }
  return runs
}

export async function generateWordDocument(
  title: string,
  content: string,
  options: DocumentOptions
): Promise<Buffer> {
  const dateStr = formatDate(options.date)
  const blocks = parseMarkdownBlocks(content)
  const bodyChildren = markdownToDocxParagraphs(blocks)

  const doc = new DocxDocument({
    creator: options.author ?? BRAND.centreName,
    title,
    description: `${title} - ${BRAND.centreName}`,
    sections: [
      {
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  ...(LOGO_BUFFER
                    ? [new ImageRun({
                        data: LOGO_BUFFER,
                        transformation: { width: 80, height: 36 },
                        type: 'jpg',
                      })]
                    : []),
                  new TextRun({
                    text: BRAND.centreName,
                    bold: true,
                    color: '470DA8',
                    size: 22,
                  }),
                  new TextRun({
                    text: `\t${dateStr}`,
                    size: 18,
                    color: '666666',
                  }),
                ],
                tabStops: [
                  {
                    type: AlignmentType.RIGHT,
                    position: 9000,
                  },
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: BRAND.tagline,
                    size: 16,
                    color: '999999',
                  }),
                  new TextRun({
                    text: '   |   Page ',
                    size: 16,
                    color: '999999',
                  }),
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 16,
                    color: '999999',
                  }),
                  new TextRun({
                    text: ' of ',
                    size: 16,
                    color: '999999',
                  }),
                  new TextRun({
                    children: [PageNumber.TOTAL_PAGES],
                    size: 16,
                    color: '999999',
                  }),
                ],
              }),
            ],
          }),
        },
        properties: {
          page: {
            size: { width: 11906, height: 16838 }, // A4
            margin: { top: 1440, right: 1080, bottom: 1440, left: 1080 },
            pageNumbers: { start: 1 },
          },
        },
        children: [
          // Title
          new Paragraph({
            heading: HeadingLevel.TITLE,
            children: [
              new TextRun({
                text: title,
                bold: true,
                color: '470DA8',
                size: 44,
              }),
            ],
            spacing: { after: 120 },
            border: {
              bottom: {
                color: '470DA8',
                style: BorderStyle.SINGLE,
                size: 6,
                space: 8,
              },
            },
          }),
          // Meta info
          ...(options.recipient
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `Prepared for: ${options.recipient}`,
                      color: '666666',
                      size: 20,
                    }),
                  ],
                }),
              ]
            : []),
          ...(options.author
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `Author: ${options.author}`,
                      color: '666666',
                      size: 20,
                    }),
                  ],
                }),
              ]
            : []),
          new Paragraph({ spacing: { after: 200 } }),
          // Body
          ...(bodyChildren as Paragraph[]),
        ],
      },
    ],
  })

  const buffer = await Packer.toBuffer(doc)
  return Buffer.from(buffer)
}

// ---------------------------------------------------------------------------
// 3. Excel Document — exceljs
// ---------------------------------------------------------------------------

export async function generateExcelDocument(
  title: string,
  content: string,
  options: DocumentOptions
): Promise<Buffer> {
  const dateStr = formatDate(options.date)
  const blocks = parseMarkdownBlocks(content)

  const workbook = new ExcelJS.Workbook()
  workbook.creator = options.author ?? BRAND.centreName
  workbook.created = new Date()

  const sheetName = title.substring(0, 31).replace(/[*?:/\\[\]]/g, '') // Excel 31-char limit
  const sheet = workbook.addWorksheet(sheetName)

  // Header row
  const headerRow = sheet.addRow([title, '', dateStr])
  headerRow.height = 30
  headerRow.eachCell((cell) => {
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 14 }
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF470DA8' },
    }
    cell.alignment = { vertical: 'middle' }
  })
  sheet.mergeCells('A1:B1')

  // Meta row
  if (options.recipient || options.author) {
    const metaParts: string[] = []
    if (options.recipient) metaParts.push(`Prepared for: ${options.recipient}`)
    if (options.author) metaParts.push(`Author: ${options.author}`)
    const metaRow = sheet.addRow([metaParts.join('  |  ')])
    metaRow.eachCell((cell) => {
      cell.font = { color: { argb: 'FF666666' }, size: 10, italic: true }
    })
  }

  sheet.addRow([]) // blank separator

  // Body content
  for (const block of blocks) {
    switch (block.type) {
      case 'heading': {
        const row = sheet.addRow([stripInlineMarkdown(block.text)])
        row.eachCell((cell) => {
          cell.font = {
            bold: true,
            size: block.level === 1 ? 14 : block.level === 2 ? 12 : 11,
            color: { argb: 'FF470DA8' },
          }
        })
        break
      }

      case 'table': {
        if (block.rows && block.rows.length > 0) {
          block.rows.forEach((rowData, ri) => {
            const row = sheet.addRow(rowData.map(stripInlineMarkdown))
            if (ri === 0) {
              row.eachCell((cell) => {
                cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10 }
                cell.fill = {
                  type: 'pattern',
                  pattern: 'solid',
                  fgColor: { argb: 'FF470DA8' },
                }
                cell.border = {
                  bottom: { style: 'thin', color: { argb: 'FF470DA8' } },
                }
              })
            } else {
              row.eachCell((cell) => {
                cell.border = {
                  bottom: { style: 'thin', color: { argb: 'FFDDDDDD' } },
                }
              })
            }
          })
        }
        break
      }

      default: {
        const text = stripInlineMarkdown(block.text)
        if (text.trim()) {
          sheet.addRow([text])
        }
        break
      }
    }
  }

  // Auto-width columns
  sheet.columns.forEach((column) => {
    let maxLength = 10
    column.eachCell?.({ includeEmpty: false }, (cell) => {
      const cellLength = cell.value ? String(cell.value).length : 0
      if (cellLength > maxLength) maxLength = cellLength
    })
    column.width = Math.min(maxLength + 4, 80)
  })

  // Footer row
  sheet.addRow([])
  const footerRow = sheet.addRow([BRAND.tagline])
  footerRow.eachCell((cell) => {
    cell.font = { size: 8, color: { argb: 'FF999999' }, italic: true }
  })

  const arrayBuffer = await workbook.xlsx.writeBuffer()
  return Buffer.from(arrayBuffer)
}

// ---------------------------------------------------------------------------
// 4. HTML Document — markdown-it
// ---------------------------------------------------------------------------

export function generateHtmlDocument(
  title: string,
  content: string,
  options: DocumentOptions
): string {
  const dateStr = formatDate(options.date)
  const renderedBody = md.render(content)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} — ${BRAND.centreName}</title>
  <style>
    :root {
      --brand-primary: ${BRAND.primary};
      --brand-primary-light: #6b3fbf;
      --text-color: #1a1a1a;
      --text-muted: #666666;
      --border-color: #e0e0e0;
      --bg-light: #f8f7fc;
    }

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      color: var(--text-color);
      line-height: 1.7;
      background: #ffffff;
      max-width: 900px;
      margin: 0 auto;
      padding: 0 24px;
    }

    header {
      background: var(--brand-primary);
      color: #ffffff;
      padding: 16px 40px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin: 0 -24px;
    }

    header .centre-name {
      font-size: 16px;
      font-weight: 700;
      letter-spacing: 0.02em;
    }

    header .date {
      font-size: 13px;
      opacity: 0.9;
    }

    .title-section {
      padding: 32px 0 20px;
      border-bottom: 3px solid var(--brand-primary);
      margin-bottom: 32px;
    }

    .title-section h1 {
      font-size: 28px;
      font-weight: 700;
      color: var(--brand-primary);
      margin-bottom: 8px;
    }

    .title-section .meta {
      font-size: 14px;
      color: var(--text-muted);
    }

    .content h1 { font-size: 24px; color: var(--brand-primary); margin: 28px 0 12px; font-weight: 700; }
    .content h2 { font-size: 20px; color: var(--brand-primary-light); margin: 24px 0 10px; font-weight: 600; }
    .content h3 { font-size: 17px; color: #333; margin: 20px 0 8px; font-weight: 600; }
    .content h4, .content h5, .content h6 { font-size: 15px; color: #444; margin: 16px 0 6px; font-weight: 600; }

    .content p { margin-bottom: 14px; font-size: 15px; }

    .content ul, .content ol { margin: 0 0 14px 24px; }
    .content li { margin-bottom: 4px; font-size: 15px; }

    .content blockquote {
      border-left: 4px solid var(--brand-primary);
      padding: 12px 20px;
      margin: 16px 0;
      background: var(--bg-light);
      color: #444;
      font-style: italic;
      border-radius: 0 4px 4px 0;
    }

    .content pre {
      background: #f4f4f4;
      padding: 16px;
      border-radius: 6px;
      overflow-x: auto;
      margin: 16px 0;
      font-size: 13px;
      line-height: 1.5;
    }

    .content code {
      font-family: 'SF Mono', SFMono-Regular, Consolas, 'Liberation Mono', Menlo, monospace;
      font-size: 0.9em;
    }

    .content p code, .content li code {
      background: #f0eef5;
      padding: 2px 6px;
      border-radius: 3px;
    }

    .content table {
      width: 100%;
      border-collapse: collapse;
      margin: 16px 0;
      font-size: 14px;
    }

    .content table th {
      background: var(--brand-primary);
      color: #ffffff;
      padding: 10px 14px;
      text-align: left;
      font-weight: 600;
    }

    .content table td {
      padding: 10px 14px;
      border-bottom: 1px solid var(--border-color);
    }

    .content table tr:nth-child(even) td {
      background: var(--bg-light);
    }

    .content strong { font-weight: 600; }

    .content a {
      color: var(--brand-primary);
      text-decoration: none;
      border-bottom: 1px solid transparent;
      transition: border-color 0.2s;
    }

    .content a:hover { border-bottom-color: var(--brand-primary); }

    footer {
      margin-top: 48px;
      padding: 16px 0;
      border-top: 1px solid var(--border-color);
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: var(--text-muted);
    }

    @media print {
      body { max-width: none; padding: 0; }
      header {
        margin: 0;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      .content table th {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
      footer { page-break-inside: avoid; }
      .title-section { page-break-after: avoid; }
      h1, h2, h3 { page-break-after: avoid; }
      table, figure { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <header>
    ${LOGO_BASE64 ? `<img src="${LOGO_BASE64}" alt="Kiros" style="height:36px;width:auto;margin-right:12px;">` : ''}
    <span class="centre-name">${escapeHtml(BRAND.centreName)}</span>
    <span class="date">${escapeHtml(dateStr)}</span>
  </header>

  <div class="title-section">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">
      ${options.recipient ? `<div>Prepared for: ${escapeHtml(options.recipient)}</div>` : ''}
      ${options.author ? `<div>Author: ${escapeHtml(options.author)}</div>` : ''}
    </div>
  </div>

  <div class="content">
    ${renderedBody}
  </div>

  <footer>
    <span>${escapeHtml(BRAND.tagline)}</span>
    <span>${escapeHtml(BRAND.centreName)} &mdash; ${escapeHtml(BRAND.location)}</span>
  </footer>
</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}
