import type { TableDef, RelationshipDef } from './report-types'

// ============================================
// REPORTING EXTRACT WIZARD - SCHEMA METADATA
// ============================================
// Single source of truth for all extractable tables, fields, and relationships.
// Every table name / column name here is validated against this whitelist
// before being used in queries.

// ─── Table Definitions ───────────────────────────────────────────────────────

export const TABLE_SCHEMA: TableDef[] = [
  // ── QA & Compliance ──────────────────────────────────────────────────────
  {
    name: 'qa_elements',
    label: 'QA Elements',
    category: 'QA & Compliance',
    description: 'National Quality Standard elements (40 standards across 7 quality areas)',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'qa_number', label: 'QA Number', type: 'number' },
      { column: 'qa_name', label: 'QA Name', type: 'text' },
      { column: 'standard_number', label: 'Standard Number', type: 'text' },
      { column: 'standard_name', label: 'Standard Name', type: 'text' },
      { column: 'element_code', label: 'Element Code', type: 'text' },
      { column: 'element_name', label: 'Element Name', type: 'text' },
      { column: 'concept', label: 'Concept', type: 'text' },
      { column: 'current_rating', label: 'Current Rating', type: 'enum', enumValues: ['not_met', 'met', 'working_towards', 'meeting', 'exceeding'] },
      { column: 'target_rating', label: 'Target Rating', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['not_started', 'in_progress', 'action_taken', 'ready_for_review', 'completed'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'officer_finding', label: 'Officer Finding', type: 'text' },
      { column: 'our_response', label: 'Our Response', type: 'text' },
      { column: 'actions_taken', label: 'Actions Taken', type: 'text' },
      { column: 'meeting_criteria', label: 'Meeting Criteria', type: 'text' },
      { column: 'exceeding_criteria', label: 'Exceeding Criteria', type: 'text' },
      { column: 'training_points', label: 'Training Points', type: 'text' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'element_actions',
    label: 'Element Actions',
    category: 'QA & Compliance',
    description: 'Actions linked to QA elements for improvement',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'element_id', label: 'Element ID', type: 'number' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'steps', label: 'Steps', type: 'json' },
      { column: 'prerequisites', label: 'Prerequisites', type: 'array' },
      { column: 'evidence_required', label: 'Evidence Required', type: 'text' },
      { column: 'evidence_files', label: 'Evidence Files', type: 'array' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['not_started', 'in_progress', 'blocked', 'completed'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'compliance_items',
    label: 'Compliance Items',
    category: 'QA & Compliance',
    description: 'Regulatory compliance tracking items',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'regulation', label: 'Regulation', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['action_required', 'in_progress', 'completed', 'ongoing'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'evidence', label: 'Evidence', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },

  // ── Tasks & Activity ─────────────────────────────────────────────────────
  {
    name: 'tasks',
    label: 'Tasks',
    category: 'Tasks & Activity',
    description: 'Task board items with priority and status tracking',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['todo', 'in_progress', 'done'] },
      { column: 'priority', label: 'Priority', type: 'enum', enumValues: ['low', 'medium', 'high', 'urgent'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'qa_element_id', label: 'QA Element ID', type: 'number' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'comments',
    label: 'Comments',
    category: 'Tasks & Activity',
    description: 'Comments on elements, tasks, documents, and training',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'entity_type', label: 'Entity Type', type: 'enum', enumValues: ['element', 'task', 'document', 'training'] },
      { column: 'entity_id', label: 'Entity ID', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'activity_log',
    label: 'Activity Log',
    category: 'Tasks & Activity',
    description: 'Audit trail of all actions in the platform',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'action', label: 'Action', type: 'text' },
      { column: 'entity_type', label: 'Entity Type', type: 'text' },
      { column: 'entity_id', label: 'Entity ID', type: 'text' },
      { column: 'details', label: 'Details', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'form_submissions',
    label: 'Form Submissions',
    category: 'Tasks & Activity',
    description: 'Submitted forms (reflections, minutes, drills, reviews, etc.)',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'form_type', label: 'Form Type', type: 'enum', enumValues: ['weekly_reflection', 'meeting_minutes', 'drill_reflection', 'family_collaboration', 'performance_review', 'family_survey', 'learning_profile', 'casual_induction'] },
      { column: 'data', label: 'Form Data', type: 'json' },
      { column: 'submitted_by', label: 'Submitted By (User ID)', type: 'uuid' },
      { column: 'room', label: 'Room', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['draft', 'submitted', 'reviewed'] },
      { column: 'reviewed_by', label: 'Reviewed By (User ID)', type: 'uuid' },
      { column: 'reviewed_at', label: 'Reviewed At', type: 'datetime' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },

  // ── Documents ────────────────────────────────────────────────────────────
  {
    name: 'documents',
    label: 'Documents',
    category: 'Documents',
    description: 'Uploaded documents and files',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'file_path', label: 'File Path', type: 'text' },
      { column: 'file_size', label: 'File Size (bytes)', type: 'number' },
      { column: 'file_type', label: 'File Type', type: 'text' },
      { column: 'qa_area', label: 'QA Area', type: 'number' },
      { column: 'category', label: 'Category', type: 'text' },
      { column: 'uploaded_by', label: 'Uploaded By (User ID)', type: 'uuid' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── Checklists ───────────────────────────────────────────────────────────
  {
    name: 'checklist_categories',
    label: 'Checklist Categories',
    category: 'Checklists',
    description: 'Categories for organising checklists',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'icon', label: 'Icon', type: 'text' },
      { column: 'color', label: 'Colour', type: 'text' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'checklist_templates',
    label: 'Checklist Templates',
    category: 'Checklists',
    description: 'Reusable checklist templates with items and scheduling',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'category_id', label: 'Category ID', type: 'number' },
      { column: 'frequency', label: 'Frequency', type: 'enum', enumValues: ['daily', 'weekly', 'monthly', 'quarterly', 'annual', 'event_triggered'] },
      { column: 'frequency_days', label: 'Frequency Days', type: 'array' },
      { column: 'frequency_day_of_month', label: 'Day of Month', type: 'number' },
      { column: 'frequency_month', label: 'Month', type: 'number' },
      { column: 'items', label: 'Items', type: 'json' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'assignable_roles', label: 'Assignable Roles', type: 'array' },
      { column: 'is_system_template', label: 'System Template', type: 'boolean' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['active', 'draft', 'archived'] },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'checklist_schedules',
    label: 'Checklist Schedules',
    category: 'Checklists',
    description: 'Scheduling rules for checklist templates',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'template_id', label: 'Template ID', type: 'uuid' },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'assigned_role', label: 'Assigned Role', type: 'enum', enumValues: ['admin', 'manager', 'ns', 'el', 'educator'] },
      { column: 'due_time', label: 'Due Time', type: 'text' },
      { column: 'auto_create', label: 'Auto Create', type: 'boolean' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['active', 'paused'] },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'checklist_instances',
    label: 'Checklist Instances',
    category: 'Checklists',
    description: 'Completed or in-progress checklist instances',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'template_id', label: 'Template ID', type: 'uuid' },
      { column: 'schedule_id', label: 'Schedule ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'due_time', label: 'Due Time', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['pending', 'in_progress', 'completed', 'overdue', 'skipped'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'completed_by', label: 'Completed By (User ID)', type: 'uuid' },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
      { column: 'responses', label: 'Responses', type: 'json' },
      { column: 'items_snapshot', label: 'Items Snapshot', type: 'json' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'total_items', label: 'Total Items', type: 'number' },
      { column: 'completed_items', label: 'Completed Items', type: 'number' },
      { column: 'failed_items', label: 'Failed Items', type: 'number' },
      { column: 'event_type', label: 'Event Type', type: 'text' },
      { column: 'event_description', label: 'Event Description', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'smart_tickets',
    label: 'Smart Tickets',
    category: 'Checklists',
    description: 'Auto-generated tickets from failed checklist items',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'checklist_instance_id', label: 'Checklist Instance ID', type: 'uuid' },
      { column: 'checklist_item_id', label: 'Checklist Item ID', type: 'text' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'priority', label: 'Priority', type: 'enum', enumValues: ['low', 'medium', 'high', 'critical'] },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['open', 'in_progress', 'resolved', 'closed', 'wont_fix'] },
      { column: 'assigned_to', label: 'Assigned To (User ID)', type: 'uuid' },
      { column: 'resolved_by', label: 'Resolved By (User ID)', type: 'uuid' },
      { column: 'resolved_at', label: 'Resolved At', type: 'datetime' },
      { column: 'resolution_notes', label: 'Resolution Notes', type: 'text' },
      { column: 'evidence_photos', label: 'Evidence Photos', type: 'array' },
      { column: 'related_qa', label: 'Related QA', type: 'number' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },

  // ── Policies ─────────────────────────────────────────────────────────────
  {
    name: 'policy_categories',
    label: 'Policy Categories',
    category: 'Policies',
    description: 'Categories for organising policies',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'icon', label: 'Icon', type: 'text' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'policies',
    label: 'Policies',
    category: 'Policies',
    description: 'Policy documents with versioning and review tracking',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'category_id', label: 'Category ID', type: 'number' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'summary', label: 'Summary', type: 'text' },
      { column: 'version', label: 'Version', type: 'number' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['draft', 'under_review', 'approved', 'published', 'archived'] },
      { column: 'review_frequency', label: 'Review Frequency', type: 'enum', enumValues: ['monthly', 'quarterly', 'biannual', 'annual', 'biennial'] },
      { column: 'next_review_date', label: 'Next Review Date', type: 'date' },
      { column: 'last_reviewed_at', label: 'Last Reviewed At', type: 'datetime' },
      { column: 'last_reviewed_by', label: 'Last Reviewed By (User ID)', type: 'uuid' },
      { column: 'approved_by', label: 'Approved By (User ID)', type: 'uuid' },
      { column: 'approved_at', label: 'Approved At', type: 'datetime' },
      { column: 'published_at', label: 'Published At', type: 'datetime' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'related_regulations', label: 'Related Regulations', type: 'text' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'owner_id', label: 'Owner (User ID)', type: 'uuid' },
      { column: 'is_family_facing', label: 'Family Facing', type: 'boolean' },
      { column: 'tags', label: 'Tags', type: 'array' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'policy_versions',
    label: 'Policy Versions',
    category: 'Policies',
    description: 'Historical versions of policies',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'policy_id', label: 'Policy ID', type: 'uuid' },
      { column: 'version', label: 'Version', type: 'number' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'change_summary', label: 'Change Summary', type: 'text' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'policy_acknowledgements',
    label: 'Policy Acknowledgements',
    category: 'Policies',
    description: 'Staff acknowledgements of policies',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'policy_id', label: 'Policy ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'version_acknowledged', label: 'Version Acknowledged', type: 'number' },
      { column: 'acknowledged_at', label: 'Acknowledged At', type: 'datetime' },
      { column: 'signature_data', label: 'Signature Data', type: 'text' },
    ],
  },

  // ── Rostering & Staff ────────────────────────────────────────────────────
  {
    name: 'profiles',
    label: 'Staff Profiles',
    category: 'Rostering & Staff',
    description: 'Staff member profiles with roles and permissions',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'email', label: 'Email', type: 'text' },
      { column: 'full_name', label: 'Full Name', type: 'text' },
      { column: 'role', label: 'Role', type: 'enum', enumValues: ['admin', 'manager', 'ns', 'el', 'educator'] },
      { column: 'avatar_url', label: 'Avatar URL', type: 'text' },
      { column: 'notify_comments', label: 'Notify Comments', type: 'boolean' },
      { column: 'notify_status_changes', label: 'Notify Status Changes', type: 'boolean' },
      { column: 'notify_assignments', label: 'Notify Assignments', type: 'boolean' },
      { column: 'allowed_pages', label: 'Allowed Pages', type: 'array' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'rooms',
    label: 'Rooms',
    category: 'Rostering & Staff',
    description: 'Centre rooms with capacity and ratio information',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'age_group', label: 'Age Group', type: 'enum', enumValues: ['0-2', '2-3', '3-5', 'school_age', 'mixed'] },
      { column: 'licensed_capacity', label: 'Licensed Capacity', type: 'number' },
      { column: 'ratio_children', label: 'Ratio Children', type: 'number' },
      { column: 'ratio_educators', label: 'Ratio Educators', type: 'number' },
      { column: 'color', label: 'Colour', type: 'text' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'is_active', label: 'Active', type: 'boolean' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'staff_qualifications',
    label: 'Staff Qualifications',
    category: 'Rostering & Staff',
    description: 'Staff qualifications, certifications, and expiry tracking',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'qualification_type', label: 'Qualification Type', type: 'enum', enumValues: ['cert_iii', 'diploma', 'ect_degree', 'working_towards_cert_iii', 'working_towards_diploma', 'working_towards_ect', 'first_aid', 'cpr', 'anaphylaxis', 'asthma', 'child_protection', 'wwcc', 'food_safety', 'other'] },
      { column: 'certificate_number', label: 'Certificate Number', type: 'text' },
      { column: 'issuing_body', label: 'Issuing Body', type: 'text' },
      { column: 'issue_date', label: 'Issue Date', type: 'date' },
      { column: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['current', 'expiring_soon', 'expired', 'pending', 'not_applicable'] },
      { column: 'document_url', label: 'Document URL', type: 'text' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'roster_shifts',
    label: 'Roster Shifts',
    category: 'Rostering & Staff',
    description: 'Individual shift assignments for staff',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'shift_date', label: 'Shift Date', type: 'date' },
      { column: 'start_time', label: 'Start Time', type: 'text' },
      { column: 'end_time', label: 'End Time', type: 'text' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'room_id', label: 'Room ID', type: 'number' },
      { column: 'shift_type', label: 'Shift Type', type: 'enum', enumValues: ['regular', 'programming_time', 'break_cover', 'casual', 'training', 'admin', 'excursion'] },
      { column: 'role_required', label: 'Role Required', type: 'enum', enumValues: ['educator', 'ect', 'diploma', 'responsible_person', 'first_aid', 'any'] },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_show'] },
      { column: 'break_start', label: 'Break Start', type: 'text' },
      { column: 'break_end', label: 'Break End', type: 'text' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'template_id', label: 'Template ID', type: 'uuid' },
      { column: 'is_published', label: 'Published', type: 'boolean' },
      { column: 'published_at', label: 'Published At', type: 'datetime' },
      { column: 'published_by', label: 'Published By (User ID)', type: 'uuid' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'roster_templates',
    label: 'Roster Templates',
    category: 'Rostering & Staff',
    description: 'Reusable roster shift patterns',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'shifts', label: 'Shifts', type: 'json' },
      { column: 'is_active', label: 'Active', type: 'boolean' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'leave_requests',
    label: 'Leave Requests',
    category: 'Rostering & Staff',
    description: 'Staff leave applications and approvals',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'leave_type', label: 'Leave Type', type: 'enum', enumValues: ['annual', 'sick', 'personal', 'parental', 'unpaid', 'professional_development', 'other'] },
      { column: 'start_date', label: 'Start Date', type: 'date' },
      { column: 'end_date', label: 'End Date', type: 'date' },
      { column: 'is_partial', label: 'Partial Day', type: 'boolean' },
      { column: 'partial_start_time', label: 'Partial Start Time', type: 'text' },
      { column: 'partial_end_time', label: 'Partial End Time', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['pending', 'approved', 'declined', 'cancelled'] },
      { column: 'reason', label: 'Reason', type: 'text' },
      { column: 'approved_by', label: 'Approved By (User ID)', type: 'uuid' },
      { column: 'approved_at', label: 'Approved At', type: 'datetime' },
      { column: 'decline_reason', label: 'Decline Reason', type: 'text' },
      { column: 'coverage_arranged', label: 'Coverage Arranged', type: 'boolean' },
      { column: 'covering_user_id', label: 'Covering User ID', type: 'uuid' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'programming_time',
    label: 'Programming Time',
    category: 'Rostering & Staff',
    description: 'Weekly programming time allocation for educators',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'week_starting', label: 'Week Starting', type: 'date' },
      { column: 'planned_hours', label: 'Planned Hours', type: 'number' },
      { column: 'actual_hours', label: 'Actual Hours', type: 'number' },
      { column: 'covering_shift_ids', label: 'Covering Shift IDs', type: 'array' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['planned', 'scheduled', 'completed', 'missed'] },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'casual_pool',
    label: 'Casual Pool',
    category: 'Rostering & Staff',
    description: 'Casual and relief staff pool',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'full_name', label: 'Full Name', type: 'text' },
      { column: 'email', label: 'Email', type: 'text' },
      { column: 'phone', label: 'Phone', type: 'text' },
      { column: 'qualification_level', label: 'Qualification Level', type: 'text' },
      { column: 'has_first_aid', label: 'Has First Aid', type: 'boolean' },
      { column: 'has_wwcc', label: 'Has WWCC', type: 'boolean' },
      { column: 'wwcc_expiry', label: 'WWCC Expiry', type: 'date' },
      { column: 'preferred_rooms', label: 'Preferred Rooms', type: 'array' },
      { column: 'preferred_age_groups', label: 'Preferred Age Groups', type: 'array' },
      { column: 'availability', label: 'Availability', type: 'json' },
      { column: 'rating', label: 'Rating', type: 'number' },
      { column: 'total_shifts', label: 'Total Shifts', type: 'number' },
      { column: 'last_shift_date', label: 'Last Shift Date', type: 'date' },
      { column: 'is_agency', label: 'Agency Staff', type: 'boolean' },
      { column: 'agency_name', label: 'Agency Name', type: 'text' },
      { column: 'hourly_rate', label: 'Hourly Rate', type: 'number' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['active', 'inactive', 'blacklisted'] },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'staff_availability',
    label: 'Staff Availability',
    category: 'Rostering & Staff',
    description: 'Weekly availability patterns for staff',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'day_of_week', label: 'Day of Week (0=Sun)', type: 'number' },
      { column: 'start_time', label: 'Start Time', type: 'text' },
      { column: 'end_time', label: 'End Time', type: 'text' },
      { column: 'availability_type', label: 'Type', type: 'enum', enumValues: ['available', 'preferred', 'unavailable'] },
      { column: 'effective_from', label: 'Effective From', type: 'date' },
      { column: 'effective_until', label: 'Effective Until', type: 'date' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── Training ─────────────────────────────────────────────────────────────
  {
    name: 'training_modules',
    label: 'Training Modules',
    category: 'Training',
    description: 'Training module definitions',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'duration_hours', label: 'Duration (hours)', type: 'number' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'related_qa', label: 'Related QA', type: 'text' },
      { column: 'related_regulations', label: 'Related Regulations', type: 'text' },
      { column: 'resources', label: 'Resources', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'training_assignments',
    label: 'Training Assignments',
    category: 'Training',
    description: 'Training module assignments to staff',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'module_id', label: 'Module ID', type: 'number' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'assigned_by', label: 'Assigned By (User ID)', type: 'uuid' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['assigned', 'in_progress', 'completed', 'overdue'] },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
      { column: 'score', label: 'Score', type: 'number' },
      { column: 'notes', label: 'Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── LMS ──────────────────────────────────────────────────────────────────
  {
    name: 'lms_modules',
    label: 'LMS Modules',
    category: 'Learning Management',
    description: 'Learning modules with tiers and categories',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'tier', label: 'Tier', type: 'enum', enumValues: ['mandatory', 'core', 'advanced'] },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'related_element_codes', label: 'Related Element Codes', type: 'array' },
      { column: 'duration_minutes', label: 'Duration (minutes)', type: 'number' },
      { column: 'category', label: 'Category', type: 'text' },
      { column: 'renewal_frequency', label: 'Renewal Frequency', type: 'enum', enumValues: ['annual', 'biennial', 'triennial', 'once'] },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['draft', 'published', 'archived'] },
      { column: 'thumbnail_url', label: 'Thumbnail URL', type: 'text' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_module_sections',
    label: 'LMS Module Sections',
    category: 'Learning Management',
    description: 'Content sections within learning modules',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'module_id', label: 'Module ID', type: 'uuid' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'section_type', label: 'Section Type', type: 'enum', enumValues: ['content', 'video', 'quiz', 'reflection', 'action_step'] },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'video_url', label: 'Video URL', type: 'text' },
      { column: 'estimated_minutes', label: 'Estimated Minutes', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_enrollments',
    label: 'LMS Enrollments',
    category: 'Learning Management',
    description: 'Staff enrollments in learning modules',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'module_id', label: 'Module ID', type: 'uuid' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['not_started', 'in_progress', 'completed', 'expired'] },
      { column: 'assigned_by', label: 'Assigned By (User ID)', type: 'uuid' },
      { column: 'due_date', label: 'Due Date', type: 'date' },
      { column: 'started_at', label: 'Started At', type: 'datetime' },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
      { column: 'score', label: 'Score', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_section_progress',
    label: 'LMS Section Progress',
    category: 'Learning Management',
    description: 'Progress tracking for module sections',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'enrollment_id', label: 'Enrollment ID', type: 'uuid' },
      { column: 'section_id', label: 'Section ID', type: 'uuid' },
      { column: 'completed', label: 'Completed', type: 'boolean' },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_quiz_questions',
    label: 'LMS Quiz Questions',
    category: 'Learning Management',
    description: 'Quiz questions within module sections',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'section_id', label: 'Section ID', type: 'uuid' },
      { column: 'question', label: 'Question', type: 'text' },
      { column: 'question_type', label: 'Question Type', type: 'enum', enumValues: ['multiple_choice', 'true_false', 'scenario'] },
      { column: 'options', label: 'Options', type: 'json' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_quiz_responses',
    label: 'LMS Quiz Responses',
    category: 'Learning Management',
    description: 'Staff responses to quiz questions',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'enrollment_id', label: 'Enrollment ID', type: 'uuid' },
      { column: 'question_id', label: 'Question ID', type: 'uuid' },
      { column: 'selected_option', label: 'Selected Option', type: 'number' },
      { column: 'is_correct', label: 'Is Correct', type: 'boolean' },
      { column: 'answered_at', label: 'Answered At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_reflections',
    label: 'LMS Reflections',
    category: 'Learning Management',
    description: 'Staff reflection responses in learning modules',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'enrollment_id', label: 'Enrollment ID', type: 'uuid' },
      { column: 'section_id', label: 'Section ID', type: 'uuid' },
      { column: 'response', label: 'Response', type: 'text' },
      { column: 'submitted_at', label: 'Submitted At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_pathways',
    label: 'LMS Pathways',
    category: 'Learning Management',
    description: 'Learning pathways grouping multiple modules',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'tier', label: 'Tier', type: 'enum', enumValues: ['mandatory', 'core', 'advanced'] },
      { column: 'estimated_hours', label: 'Estimated Hours', type: 'number' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['draft', 'published', 'archived'] },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_pathway_modules',
    label: 'LMS Pathway Modules',
    category: 'Learning Management',
    description: 'Modules within a learning pathway',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'pathway_id', label: 'Pathway ID', type: 'uuid' },
      { column: 'module_id', label: 'Module ID', type: 'uuid' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'is_required', label: 'Required', type: 'boolean' },
    ],
  },
  {
    name: 'lms_pathway_enrollments',
    label: 'LMS Pathway Enrollments',
    category: 'Learning Management',
    description: 'Staff enrollments in learning pathways',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'pathway_id', label: 'Pathway ID', type: 'uuid' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['not_started', 'in_progress', 'completed'] },
      { column: 'started_at', label: 'Started At', type: 'datetime' },
      { column: 'completed_at', label: 'Completed At', type: 'datetime' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_pdp_goals',
    label: 'PDP Goals',
    category: 'Learning Management',
    description: 'Professional Development Plan goals',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'target_date', label: 'Target Date', type: 'date' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['active', 'completed', 'deferred'] },
      { column: 'linked_module_ids', label: 'Linked Module IDs', type: 'array' },
      { column: 'linked_pathway_ids', label: 'Linked Pathway IDs', type: 'array' },
      { column: 'evidence_notes', label: 'Evidence Notes', type: 'text' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_pdp_reviews',
    label: 'PDP Reviews',
    category: 'Learning Management',
    description: 'Professional Development Plan review records',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'reviewer_id', label: 'Reviewer ID', type: 'uuid' },
      { column: 'review_period', label: 'Review Period', type: 'text' },
      { column: 'goals_summary', label: 'Goals Summary', type: 'text' },
      { column: 'strengths', label: 'Strengths', type: 'text' },
      { column: 'areas_for_growth', label: 'Areas for Growth', type: 'text' },
      { column: 'agreed_actions', label: 'Agreed Actions', type: 'text' },
      { column: 'staff_signature', label: 'Staff Signature', type: 'text' },
      { column: 'reviewer_signature', label: 'Reviewer Signature', type: 'text' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['draft', 'submitted', 'reviewed', 'acknowledged'] },
      { column: 'reviewed_at', label: 'Reviewed At', type: 'datetime' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'lms_certificates',
    label: 'Certificates',
    category: 'Learning Management',
    description: 'Staff certificates (internal, external, qualifications)',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'certificate_type', label: 'Certificate Type', type: 'enum', enumValues: ['internal', 'external', 'qualification'] },
      { column: 'issuer', label: 'Issuer', type: 'text' },
      { column: 'issue_date', label: 'Issue Date', type: 'date' },
      { column: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { column: 'file_path', label: 'File Path', type: 'text' },
      { column: 'module_id', label: 'Module ID', type: 'uuid' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['current', 'expiring_soon', 'expired'] },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── Chat & AI ────────────────────────────────────────────────────────────
  {
    name: 'chat_conversations',
    label: 'Chat Conversations',
    category: 'Chat & AI',
    description: 'AI chat conversation threads',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'user_id', label: 'User ID', type: 'uuid' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'is_active', label: 'Active', type: 'boolean' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'chat_messages',
    label: 'Chat Messages',
    category: 'Chat & AI',
    description: 'Individual messages in AI chat conversations',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'conversation_id', label: 'Conversation ID', type: 'uuid' },
      { column: 'role', label: 'Role', type: 'enum', enumValues: ['user', 'assistant', 'system', 'tool_call', 'tool_result'] },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'metadata', label: 'Metadata', type: 'json' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'ai_suggestions',
    label: 'AI Suggestions',
    category: 'Chat & AI',
    description: 'AI-generated suggestions for quality improvement',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'suggested_by', label: 'Suggested By (User ID)', type: 'uuid' },
      { column: 'target_role', label: 'Target Role', type: 'enum', enumValues: ['admin', 'manager', 'ns', 'el', 'educator'] },
      { column: 'target_user_id', label: 'Target User ID', type: 'uuid' },
      { column: 'suggestion_type', label: 'Suggestion Type', type: 'enum', enumValues: ['daily_priority', 'qip_improvement', 'training_gap', 'checklist_improvement', 'compliance_reminder', 'family_engagement'] },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'action_type', label: 'Action Type', type: 'enum', enumValues: ['create_task', 'assign_training', 'create_checklist', 'update_element', 'view_item'] },
      { column: 'action_payload', label: 'Action Payload', type: 'json' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['pending', 'approved', 'rejected', 'actioned', 'dismissed'] },
      { column: 'reviewed_by', label: 'Reviewed By (User ID)', type: 'uuid' },
      { column: 'reviewed_at', label: 'Reviewed At', type: 'datetime' },
      { column: 'expires_at', label: 'Expires At', type: 'datetime' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── Centre & Config ──────────────────────────────────────────────────────
  {
    name: 'centre_context',
    label: 'Centre Context',
    category: 'Centre & Config',
    description: 'Extracted context items from centre documents for AI',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'document_id', label: 'Document ID', type: 'uuid' },
      { column: 'context_type', label: 'Context Type', type: 'enum', enumValues: ['qip_goal', 'qip_strategy', 'philosophy_principle', 'policy_requirement', 'procedure_step', 'service_value', 'teaching_approach', 'family_engagement', 'inclusion_practice', 'safety_protocol', 'environment_feature', 'leadership_goal'] },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'content', label: 'Content', type: 'text' },
      { column: 'related_qa', label: 'Related QA Areas', type: 'array' },
      { column: 'related_element_codes', label: 'Related Element Codes', type: 'array' },
      { column: 'source_quote', label: 'Source Quote', type: 'text' },
      { column: 'ai_generated', label: 'AI Generated', type: 'boolean' },
      { column: 'is_active', label: 'Active', type: 'boolean' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'resources',
    label: 'Resources',
    category: 'Centre & Config',
    description: 'External resource links',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'title', label: 'Title', type: 'text' },
      { column: 'url', label: 'URL', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'qa_area', label: 'QA Area', type: 'number' },
      { column: 'category', label: 'Category', type: 'text' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'service_details',
    label: 'Service Details',
    category: 'Centre & Config',
    description: 'Centre configuration key-value pairs',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'key', label: 'Key', type: 'text' },
      { column: 'value', label: 'Value', type: 'text' },
      { column: 'label', label: 'Label', type: 'text' },
      { column: 'category', label: 'Category', type: 'text' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'tags',
    label: 'Tags',
    category: 'Centre & Config',
    description: 'Tag definitions for categorising items',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'color', label: 'Colour', type: 'text' },
      { column: 'category', label: 'Category', type: 'enum', enumValues: ['qa', 'priority', 'training', 'status', 'custom'] },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },
  {
    name: 'entity_tags',
    label: 'Entity Tags',
    category: 'Centre & Config',
    description: 'Tag assignments to entities',
    fields: [
      { column: 'id', label: 'ID', type: 'number' },
      { column: 'entity_type', label: 'Entity Type', type: 'enum', enumValues: ['element', 'task', 'action', 'document', 'training'] },
      { column: 'entity_id', label: 'Entity ID', type: 'text' },
      { column: 'tag_id', label: 'Tag ID', type: 'number' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
    ],
  },

  // ── Registers ────────────────────────────────────────────────────────────
  {
    name: 'register_definitions',
    label: 'Register Definitions',
    category: 'Registers',
    description: 'Custom register templates with dynamic columns',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'icon', label: 'Icon', type: 'text' },
      { column: 'columns', label: 'Column Definitions', type: 'json' },
      { column: 'is_system_template', label: 'System Template', type: 'boolean' },
      { column: 'status', label: 'Status', type: 'enum', enumValues: ['active', 'archived'] },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
  {
    name: 'register_entries',
    label: 'Register Entries',
    category: 'Registers',
    description: 'Data entries in custom registers',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'register_id', label: 'Register ID', type: 'uuid' },
      { column: 'row_data', label: 'Row Data', type: 'json' },
      { column: 'sort_order', label: 'Sort Order', type: 'number' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'updated_by', label: 'Updated By (User ID)', type: 'uuid' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },

  // ── SharePoint ───────────────────────────────────────────────────────────
  {
    name: 'sharepoint_documents',
    label: 'SharePoint Documents',
    category: 'Documents',
    description: 'Documents synced from SharePoint',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'sharepoint_item_id', label: 'SharePoint Item ID', type: 'text' },
      { column: 'file_name', label: 'File Name', type: 'text' },
      { column: 'file_path', label: 'File Path', type: 'text' },
      { column: 'file_type', label: 'File Type', type: 'text' },
      { column: 'file_size', label: 'File Size', type: 'number' },
      { column: 'content_hash', label: 'Content Hash', type: 'text' },
      { column: 'extracted_text', label: 'Extracted Text', type: 'text' },
      { column: 'document_type', label: 'Document Type', type: 'enum', enumValues: ['qip', 'philosophy', 'policy', 'handbook', 'programming', 'procedure', 'other'] },
      { column: 'is_monitored', label: 'Monitored', type: 'boolean' },
      { column: 'last_modified_at', label: 'Last Modified', type: 'datetime' },
      { column: 'last_synced_at', label: 'Last Synced', type: 'datetime' },
      { column: 'last_processed_at', label: 'Last Processed', type: 'datetime' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },

  // ── Report Templates (self-referential) ──────────────────────────────────
  {
    name: 'report_templates',
    label: 'Saved Report Templates',
    category: 'Centre & Config',
    description: 'Saved report extract configurations',
    fields: [
      { column: 'id', label: 'ID', type: 'uuid' },
      { column: 'name', label: 'Name', type: 'text' },
      { column: 'description', label: 'Description', type: 'text' },
      { column: 'config', label: 'Configuration', type: 'json' },
      { column: 'created_by', label: 'Created By (User ID)', type: 'uuid' },
      { column: 'is_shared', label: 'Shared', type: 'boolean' },
      { column: 'created_at', label: 'Created At', type: 'datetime' },
      { column: 'updated_at', label: 'Updated At', type: 'datetime' },
    ],
  },
]

// ─── Relationships (Foreign Keys) ────────────────────────────────────────────

export const RELATIONSHIPS: RelationshipDef[] = [
  // QA & Compliance
  { id: 'element_actions->qa_elements', fromTable: 'element_actions', fromColumn: 'element_id', toTable: 'qa_elements', toColumn: 'id', label: 'Action -> QA Element', type: 'many-to-one' },
  { id: 'element_actions->profiles', fromTable: 'element_actions', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Action -> Assigned User', type: 'many-to-one', fkHint: 'element_actions_assigned_to_fkey' },
  { id: 'qa_elements->profiles', fromTable: 'qa_elements', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Element -> Assigned User', type: 'many-to-one', fkHint: 'qa_elements_assigned_to_fkey' },
  { id: 'compliance_items->profiles', fromTable: 'compliance_items', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Compliance -> Assigned User', type: 'many-to-one', fkHint: 'compliance_items_assigned_to_fkey' },

  // Tasks
  { id: 'tasks->profiles_assigned', fromTable: 'tasks', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Task -> Assigned User', type: 'many-to-one', fkHint: 'tasks_assigned_to_fkey' },
  { id: 'tasks->profiles_created', fromTable: 'tasks', fromColumn: 'created_by', toTable: 'profiles', toColumn: 'id', label: 'Task -> Created By', type: 'many-to-one', fkHint: 'tasks_created_by_fkey' },
  { id: 'tasks->qa_elements', fromTable: 'tasks', fromColumn: 'qa_element_id', toTable: 'qa_elements', toColumn: 'id', label: 'Task -> QA Element', type: 'many-to-one' },
  { id: 'comments->profiles', fromTable: 'comments', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Comment -> User', type: 'many-to-one' },
  { id: 'activity_log->profiles', fromTable: 'activity_log', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Activity -> User', type: 'many-to-one' },
  { id: 'form_submissions->profiles_submitted', fromTable: 'form_submissions', fromColumn: 'submitted_by', toTable: 'profiles', toColumn: 'id', label: 'Form -> Submitted By', type: 'many-to-one', fkHint: 'form_submissions_submitted_by_fkey' },
  { id: 'form_submissions->profiles_reviewed', fromTable: 'form_submissions', fromColumn: 'reviewed_by', toTable: 'profiles', toColumn: 'id', label: 'Form -> Reviewed By', type: 'many-to-one', fkHint: 'form_submissions_reviewed_by_fkey' },

  // Documents
  { id: 'documents->profiles', fromTable: 'documents', fromColumn: 'uploaded_by', toTable: 'profiles', toColumn: 'id', label: 'Document -> Uploaded By', type: 'many-to-one' },

  // Checklists
  { id: 'checklist_templates->checklist_categories', fromTable: 'checklist_templates', fromColumn: 'category_id', toTable: 'checklist_categories', toColumn: 'id', label: 'Template -> Category', type: 'many-to-one' },
  { id: 'checklist_templates->profiles', fromTable: 'checklist_templates', fromColumn: 'created_by', toTable: 'profiles', toColumn: 'id', label: 'Template -> Created By', type: 'many-to-one' },
  { id: 'checklist_schedules->checklist_templates', fromTable: 'checklist_schedules', fromColumn: 'template_id', toTable: 'checklist_templates', toColumn: 'id', label: 'Schedule -> Template', type: 'many-to-one' },
  { id: 'checklist_schedules->profiles', fromTable: 'checklist_schedules', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Schedule -> Assigned User', type: 'many-to-one' },
  { id: 'checklist_instances->checklist_templates', fromTable: 'checklist_instances', fromColumn: 'template_id', toTable: 'checklist_templates', toColumn: 'id', label: 'Instance -> Template', type: 'many-to-one' },
  { id: 'checklist_instances->profiles_assigned', fromTable: 'checklist_instances', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Instance -> Assigned User', type: 'many-to-one', fkHint: 'checklist_instances_assigned_to_fkey' },
  { id: 'checklist_instances->profiles_completed', fromTable: 'checklist_instances', fromColumn: 'completed_by', toTable: 'profiles', toColumn: 'id', label: 'Instance -> Completed By', type: 'many-to-one', fkHint: 'checklist_instances_completed_by_fkey' },
  { id: 'smart_tickets->checklist_instances', fromTable: 'smart_tickets', fromColumn: 'checklist_instance_id', toTable: 'checklist_instances', toColumn: 'id', label: 'Ticket -> Checklist Instance', type: 'many-to-one' },
  { id: 'smart_tickets->profiles_assigned', fromTable: 'smart_tickets', fromColumn: 'assigned_to', toTable: 'profiles', toColumn: 'id', label: 'Ticket -> Assigned User', type: 'many-to-one', fkHint: 'smart_tickets_assigned_to_fkey' },
  { id: 'smart_tickets->profiles_resolved', fromTable: 'smart_tickets', fromColumn: 'resolved_by', toTable: 'profiles', toColumn: 'id', label: 'Ticket -> Resolved By', type: 'many-to-one', fkHint: 'smart_tickets_resolved_by_fkey' },

  // Policies
  { id: 'policies->policy_categories', fromTable: 'policies', fromColumn: 'category_id', toTable: 'policy_categories', toColumn: 'id', label: 'Policy -> Category', type: 'many-to-one' },
  { id: 'policies->profiles_created', fromTable: 'policies', fromColumn: 'created_by', toTable: 'profiles', toColumn: 'id', label: 'Policy -> Created By', type: 'many-to-one', fkHint: 'policies_created_by_fkey' },
  { id: 'policies->profiles_owner', fromTable: 'policies', fromColumn: 'owner_id', toTable: 'profiles', toColumn: 'id', label: 'Policy -> Owner', type: 'many-to-one', fkHint: 'policies_owner_id_fkey' },
  { id: 'policy_versions->policies', fromTable: 'policy_versions', fromColumn: 'policy_id', toTable: 'policies', toColumn: 'id', label: 'Version -> Policy', type: 'many-to-one' },
  { id: 'policy_acknowledgements->policies', fromTable: 'policy_acknowledgements', fromColumn: 'policy_id', toTable: 'policies', toColumn: 'id', label: 'Acknowledgement -> Policy', type: 'many-to-one' },
  { id: 'policy_acknowledgements->profiles', fromTable: 'policy_acknowledgements', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Acknowledgement -> User', type: 'many-to-one' },

  // Rostering
  { id: 'staff_qualifications->profiles', fromTable: 'staff_qualifications', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Qualification -> Staff Member', type: 'many-to-one' },
  { id: 'roster_shifts->profiles', fromTable: 'roster_shifts', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Shift -> Staff Member', type: 'many-to-one' },
  { id: 'roster_shifts->rooms', fromTable: 'roster_shifts', fromColumn: 'room_id', toTable: 'rooms', toColumn: 'id', label: 'Shift -> Room', type: 'many-to-one' },
  { id: 'leave_requests->profiles_user', fromTable: 'leave_requests', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Leave -> Staff Member', type: 'many-to-one', fkHint: 'leave_requests_user_id_fkey' },
  { id: 'leave_requests->profiles_approved', fromTable: 'leave_requests', fromColumn: 'approved_by', toTable: 'profiles', toColumn: 'id', label: 'Leave -> Approved By', type: 'many-to-one', fkHint: 'leave_requests_approved_by_fkey' },
  { id: 'programming_time->profiles', fromTable: 'programming_time', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Programming Time -> Staff', type: 'many-to-one' },

  // Training
  { id: 'training_assignments->training_modules', fromTable: 'training_assignments', fromColumn: 'module_id', toTable: 'training_modules', toColumn: 'id', label: 'Assignment -> Module', type: 'many-to-one' },
  { id: 'training_assignments->profiles_user', fromTable: 'training_assignments', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Assignment -> Staff', type: 'many-to-one', fkHint: 'training_assignments_user_id_fkey' },
  { id: 'training_assignments->profiles_assigned', fromTable: 'training_assignments', fromColumn: 'assigned_by', toTable: 'profiles', toColumn: 'id', label: 'Assignment -> Assigned By', type: 'many-to-one', fkHint: 'training_assignments_assigned_by_fkey' },

  // LMS
  { id: 'lms_module_sections->lms_modules', fromTable: 'lms_module_sections', fromColumn: 'module_id', toTable: 'lms_modules', toColumn: 'id', label: 'Section -> Module', type: 'many-to-one' },
  { id: 'lms_enrollments->profiles', fromTable: 'lms_enrollments', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Enrollment -> Staff', type: 'many-to-one' },
  { id: 'lms_enrollments->lms_modules', fromTable: 'lms_enrollments', fromColumn: 'module_id', toTable: 'lms_modules', toColumn: 'id', label: 'Enrollment -> Module', type: 'many-to-one' },
  { id: 'lms_section_progress->lms_enrollments', fromTable: 'lms_section_progress', fromColumn: 'enrollment_id', toTable: 'lms_enrollments', toColumn: 'id', label: 'Progress -> Enrollment', type: 'many-to-one' },
  { id: 'lms_section_progress->lms_module_sections', fromTable: 'lms_section_progress', fromColumn: 'section_id', toTable: 'lms_module_sections', toColumn: 'id', label: 'Progress -> Section', type: 'many-to-one' },
  { id: 'lms_quiz_questions->lms_module_sections', fromTable: 'lms_quiz_questions', fromColumn: 'section_id', toTable: 'lms_module_sections', toColumn: 'id', label: 'Question -> Section', type: 'many-to-one' },
  { id: 'lms_quiz_responses->lms_enrollments', fromTable: 'lms_quiz_responses', fromColumn: 'enrollment_id', toTable: 'lms_enrollments', toColumn: 'id', label: 'Quiz Response -> Enrollment', type: 'many-to-one' },
  { id: 'lms_quiz_responses->lms_quiz_questions', fromTable: 'lms_quiz_responses', fromColumn: 'question_id', toTable: 'lms_quiz_questions', toColumn: 'id', label: 'Quiz Response -> Question', type: 'many-to-one' },
  { id: 'lms_reflections->lms_enrollments', fromTable: 'lms_reflections', fromColumn: 'enrollment_id', toTable: 'lms_enrollments', toColumn: 'id', label: 'Reflection -> Enrollment', type: 'many-to-one' },
  { id: 'lms_pathway_modules->lms_pathways', fromTable: 'lms_pathway_modules', fromColumn: 'pathway_id', toTable: 'lms_pathways', toColumn: 'id', label: 'Pathway Module -> Pathway', type: 'many-to-one' },
  { id: 'lms_pathway_modules->lms_modules', fromTable: 'lms_pathway_modules', fromColumn: 'module_id', toTable: 'lms_modules', toColumn: 'id', label: 'Pathway Module -> Module', type: 'many-to-one' },
  { id: 'lms_pathway_enrollments->profiles', fromTable: 'lms_pathway_enrollments', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Pathway Enrollment -> Staff', type: 'many-to-one' },
  { id: 'lms_pathway_enrollments->lms_pathways', fromTable: 'lms_pathway_enrollments', fromColumn: 'pathway_id', toTable: 'lms_pathways', toColumn: 'id', label: 'Pathway Enrollment -> Pathway', type: 'many-to-one' },
  { id: 'lms_pdp_goals->profiles', fromTable: 'lms_pdp_goals', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'PDP Goal -> Staff', type: 'many-to-one' },
  { id: 'lms_pdp_reviews->profiles_user', fromTable: 'lms_pdp_reviews', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'PDP Review -> Staff', type: 'many-to-one', fkHint: 'lms_pdp_reviews_user_id_fkey' },
  { id: 'lms_pdp_reviews->profiles_reviewer', fromTable: 'lms_pdp_reviews', fromColumn: 'reviewer_id', toTable: 'profiles', toColumn: 'id', label: 'PDP Review -> Reviewer', type: 'many-to-one', fkHint: 'lms_pdp_reviews_reviewer_id_fkey' },
  { id: 'lms_certificates->profiles', fromTable: 'lms_certificates', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Certificate -> Staff', type: 'many-to-one' },
  { id: 'lms_certificates->lms_modules', fromTable: 'lms_certificates', fromColumn: 'module_id', toTable: 'lms_modules', toColumn: 'id', label: 'Certificate -> Module', type: 'many-to-one' },

  // Chat & AI
  { id: 'chat_conversations->profiles', fromTable: 'chat_conversations', fromColumn: 'user_id', toTable: 'profiles', toColumn: 'id', label: 'Conversation -> User', type: 'many-to-one' },
  { id: 'chat_messages->chat_conversations', fromTable: 'chat_messages', fromColumn: 'conversation_id', toTable: 'chat_conversations', toColumn: 'id', label: 'Message -> Conversation', type: 'many-to-one' },

  // Centre & Config
  { id: 'centre_context->sharepoint_documents', fromTable: 'centre_context', fromColumn: 'document_id', toTable: 'sharepoint_documents', toColumn: 'id', label: 'Context -> SharePoint Doc', type: 'many-to-one' },
  { id: 'entity_tags->tags', fromTable: 'entity_tags', fromColumn: 'tag_id', toTable: 'tags', toColumn: 'id', label: 'Entity Tag -> Tag', type: 'many-to-one' },
  { id: 'register_entries->register_definitions', fromTable: 'register_entries', fromColumn: 'register_id', toTable: 'register_definitions', toColumn: 'id', label: 'Entry -> Register', type: 'many-to-one' },
  { id: 'report_templates->profiles', fromTable: 'report_templates', fromColumn: 'created_by', toTable: 'profiles', toColumn: 'id', label: 'Template -> Created By', type: 'many-to-one' },
]

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getTableDef(tableName: string): TableDef | undefined {
  return TABLE_SCHEMA.find(t => t.name === tableName)
}

export function getFieldDef(tableName: string, column: string) {
  const table = getTableDef(tableName)
  return table?.fields.find(f => f.column === column)
}

export function getRelationshipsForTable(tableName: string): RelationshipDef[] {
  return RELATIONSHIPS.filter(r => r.fromTable === tableName || r.toTable === tableName)
}

export function getOutgoingRelationships(tableName: string): RelationshipDef[] {
  return RELATIONSHIPS.filter(r => r.fromTable === tableName && r.type === 'many-to-one')
}

export function getTableCategories(): string[] {
  const cats = new Set(TABLE_SCHEMA.map(t => t.category))
  return Array.from(cats)
}

export function getTablesByCategory(): Record<string, TableDef[]> {
  const result: Record<string, TableDef[]> = {}
  for (const table of TABLE_SCHEMA) {
    if (!result[table.category]) result[table.category] = []
    result[table.category].push(table)
  }
  return result
}

/** Validate that a table name exists in the schema (whitelist) */
export function isValidTable(name: string): boolean {
  return TABLE_SCHEMA.some(t => t.name === name)
}

/** Validate that a column exists on a table (whitelist) */
export function isValidColumn(tableName: string, column: string): boolean {
  const table = getTableDef(tableName)
  return !!table?.fields.some(f => f.column === column)
}
