-- AI Generated Documents table
-- Tracks all documents generated by Kiros AI with SharePoint storage

CREATE TABLE IF NOT EXISTS ai_generated_documents (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  conversation_id uuid,
  message_id text,
  title text NOT NULL,
  document_type text NOT NULL CHECK (document_type IN ('report','letter','policy','plan','checklist','agenda','communication','guide','summary','other')),
  topic_folder text NOT NULL,
  markdown_content text NOT NULL,
  json_metadata jsonb NOT NULL DEFAULT '{}',
  sharepoint_folder_id text,
  sharepoint_folder_path text,
  sharepoint_urls jsonb DEFAULT '{}',
  sharepoint_item_ids jsonb DEFAULT '{}',
  format_variants text[] DEFAULT '{}',
  content_hash text,
  version integer DEFAULT 1,
  sync_status text DEFAULT 'synced' CHECK (sync_status IN ('synced','modified_externally','pending_upload','upload_failed','sync_error')),
  created_by uuid REFERENCES profiles(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  last_synced_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_ai_docs_topic ON ai_generated_documents(topic_folder);
CREATE INDEX IF NOT EXISTS idx_ai_docs_type ON ai_generated_documents(document_type);
CREATE INDEX IF NOT EXISTS idx_ai_docs_conversation ON ai_generated_documents(conversation_id);
CREATE INDEX IF NOT EXISTS idx_ai_docs_sync_status ON ai_generated_documents(sync_status);
CREATE INDEX IF NOT EXISTS idx_ai_docs_created ON ai_generated_documents(created_at DESC);

ALTER TABLE ai_generated_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_read_ai_docs" ON ai_generated_documents
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_ai_docs" ON ai_generated_documents
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_update_ai_docs" ON ai_generated_documents
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
